### PR TITLE
Changes from libappimage

### PR DESCRIPTION
**Pull request by azubieta**
Set of changes required in the new libappimage implementation

### CODE REVIEW

**Comment by probonopd** [comment]
@azubieta does this mean that consumers of libappimage need to be changed in order to be able to use the c++ based version? In this case, let's make very sure that `appimaged` is also changed appropriately once the c++ based libappimage is available for general consumption.

**Comment by azubieta** [comment]
@probonopd As far as I know, this lib is only used at `linuxdeploy` and at `libappimage`. `appimaged` uses the desktop integration functions from `libappimage` so it will receive the changes once migrated to the new implementation.

**Comment by TheAssassin** [comment]
I don't see what this is PR is supposed to add to this library. "Needed by libappimage" is a bad description. Also, it doesn't follow the same strategies re. PImpl as the rest of the code does. Please improve the description to show what this is supposed to add, and fix the use of PImpl.

**Comment by azubieta** [comment]
Closing it as no longer required.

**Pull request closed without merging**
